export type Role = "civil" | "undercover" | "mrwhite";

export type Player = {
  id: number;
  cardIndex: number; // position of the card on the board
  order: number; // order in which the card was picked
  name: string;
  role: Role;
  word: string | null;
  eliminated: boolean;
};

export interface WordPair {
  civil: string;
  undercover: string;
}

export const WORD_PAIRS: WordPair[] = [
  { civil: "Citron", undercover: "Orange" },
  { civil: "Café", undercover: "Thé" },
  { civil: "Chien", undercover: "Loup" },
  { civil: "Piscine", undercover: "Mer" },
  { civil: "Vélo", undercover: "Moto" },
  { civil: "Neige", undercover: "Pluie" },
  { civil: "Guitare", undercover: "Violon" },
  { civil: "Pizza", undercover: "Quiche" },
  { civil: "Avion", undercover: "Hélicoptère" },
  { civil: "Docteur", undercover: "Infirmier" },
  { civil: "Livre", undercover: "Magazine" },
  { civil: "Montre", undercover: "Bracelet" },
  { civil: "Chocolat", undercover: "Caramel" },
  { civil: "Plage", undercover: "Désert" },
  { civil: "Roi", undercover: "Président" },
  { civil: "Théâtre", undercover: "Cinéma" },
  { civil: "Fourchette", undercover: "Cuillère" },
  { civil: "Bougie", undercover: "Lampe" },
  { civil: "Chat", undercover: "Tigre" },
  { civil: "Train", undercover: "Métro" },
  { civil: "Bière", undercover: "Vin" },
  { civil: "Fromage", undercover: "Yaourt" },
  { civil: "Football", undercover: "Rugby" },
  { civil: "Hiver", undercover: "Automne" },
  { civil: "Sorcière", undercover: "Fée" },
  { civil: "Peinture", undercover: "Dessin" },
  { civil: "Miroir", undercover: "Fenêtre" },
  { civil: "Casquette", undercover: "Chapeau" },
  { civil: "Ordinateur", undercover: "Téléphone" },
  { civil: "Crêpe", undercover: "Gaufre" },
  { civil: "Bateau", undercover: "Sous-marin" },
  { civil: "Professeur", undercover: "Élève" },
  { civil: "Chanteur", undercover: "Danseur" },
  { civil: "Boulangerie", undercover: "Pâtisserie" },
  { civil: "Soleil", undercover: "Lune" },
  { civil: "Rivière", undercover: "Lac" },
  { civil: "Escalier", undercover: "Ascenseur" },
  { civil: "Journal", undercover: "Radio" },
  { civil: "Château", undercover: "Cathédrale" },
  { civil: "Pompier", undercover: "Policier" },
  { civil: "Bagage", undercover: "Sac à dos" },
  { civil: "Barbe", undercover: "Moustache" },
  { civil: "Piano", undercover: "Orgue" },
  { civil: "Sirop", undercover: "Miel" },
  { civil: "Tempête", undercover: "Orage" },
  { civil: "Frigo", undercover: "Congélateur" },
  { civil: "Cravate", undercover: "Écharpe" },
  { civil: "Balcon", undercover: "Terrasse" },
  { civil: "Cirque", undercover: "Zoo" },
  { civil: "Baleine", undercover: "Requin" },
  { civil: "Chaussette", undercover: "Gant" },
  { civil: "Mariage", undercover: "Anniversaire" },
  { civil: "Chameau", undercover: "Cheval" },
  { civil: "Savon", undercover: "Shampoing" },
  { civil: "Parapluie", undercover: "Imperméable" },
  { civil: "Bibliothèque", undercover: "Musée" },
  { civil: "Sandwich", undercover: "Burger" },
  { civil: "Étoile", undercover: "Planète" },
  { civil: "Jardin", undercover: "Forêt" },
  { civil: "Facteur", undercover: "Livreur" },
  { civil: "Poêle", undercover: "Casserole" },
  { civil: "Ballon", undercover: "Cerf-volant" },
  { civil: "Grenier", undercover: "Cave" },
  { civil: "Skateboard", undercover: "Trottinette" },
  { civil: "Tatouage", undercover: "Cicatrice" },
  { civil: "Poivre", undercover: "Sel" },
  { civil: "Camion", undercover: "Bus" },
  { civil: "Ampoule", undercover: "Bougie" },
  { civil: "Aquarium", undercover: "Terrarium" },
  { civil: "Confiture", undercover: "Compote" },
  { civil: "Pyjama", undercover: "Peignoir" },
  { civil: "Menteur", undercover: "Acteur" },
  { civil: "Cimetière", undercover: "Église" },
  { civil: "Ski", undercover: "Snowboard" },
  { civil: "Clavier", undercover: "Souris" },
  { civil: "Pharmacie", undercover: "Hôpital" },
  { civil: "Papillon", undercover: "Abeille" },
  { civil: "Chewing-gum", undercover: "Bonbon" },
  { civil: "Marathon", undercover: "Sprint" },
  { civil: "Aéroport", undercover: "Gare" },
  { civil: "Pomme", undercover: "Poire" },
  { civil: "Banane", undercover: "Ananas" },
  { civil: "Fraise", undercover: "Framboise" },
  { civil: "Cerise", undercover: "Prune" },
  { civil: "Melon", undercover: "Pastèque" },
  { civil: "Kiwi", undercover: "Mangue" },
  { civil: "Carotte", undercover: "Navet" },
  { civil: "Pomme de terre", undercover: "Patate douce" },
  { civil: "Tomate", undercover: "Poivron" },
  { civil: "Courgette", undercover: "Aubergine" },
  { civil: "Oignon", undercover: "Ail" },
  { civil: "Salade", undercover: "Épinard" },
  { civil: "Champignon", undercover: "Truffe" },
  { civil: "Radis", undercover: "Betterave" },
  { civil: "Citrouille", undercover: "Potiron" },
  { civil: "Noix", undercover: "Amande" },
  { civil: "Raisin", undercover: "Groseille" },
  { civil: "Avocat", undercover: "Olive" },
  { civil: "Lion", undercover: "Panthère" },
  { civil: "Éléphant", undercover: "Rhinocéros" },
  { civil: "Girafe", undercover: "Zèbre" },
  { civil: "Singe", undercover: "Gorille" },
  { civil: "Ours", undercover: "Panda" },
  { civil: "Renard", undercover: "Blaireau" },
  { civil: "Lapin", undercover: "Écureuil" },
  { civil: "Souris", undercover: "Rat" },
  { civil: "Hibou", undercover: "Chouette" },
  { civil: "Aigle", undercover: "Faucon" },
  { civil: "Perroquet", undercover: "Perruche" },
  { civil: "Pingouin", undercover: "Manchot" },
  { civil: "Grenouille", undercover: "Crapaud" },
  { civil: "Serpent", undercover: "Lézard" },
  { civil: "Tortue", undercover: "Crocodile" },
  { civil: "Dauphin", undercover: "Orque" },
  { civil: "Poulpe", undercover: "Calamar" },
  { civil: "Crabe", undercover: "Homard" },
  { civil: "Cochon", undercover: "Sanglier" },
  { civil: "Vache", undercover: "Buffle" },
  { civil: "Mouton", undercover: "Chèvre" },
  { civil: "Coq", undercover: "Poule" },
  { civil: "Canard", undercover: "Oie" },
  { civil: "Dinde", undercover: "Faisan" },
  { civil: "Araignée", undercover: "Scorpion" },
  { civil: "Fourmi", undercover: "Termite" },
  { civil: "Moustique", undercover: "Mouche" },
  { civil: "Escargot", undercover: "Limace" },
  { civil: "Hérisson", undercover: "Taupe" },
  { civil: "Chauve-souris", undercover: "Hibou" },
  { civil: "Kangourou", undercover: "Koala" },
  { civil: "Autruche", undercover: "Flamant rose" },
  { civil: "Paon", undercover: "Cygne" },
  { civil: "Loutre", undercover: "Castor" },
  { civil: "Phoque", undercover: "Morse" },
  { civil: "Méduse", undercover: "Étoile de mer" },
  { civil: "Coccinelle", undercover: "Scarabée" },
  { civil: "Ver de terre", undercover: "Chenille" },
  { civil: "Boulanger", undercover: "Boucher" },
  { civil: "Avocat", undercover: "Juge" },
  { civil: "Architecte", undercover: "Ingénieur" },
  { civil: "Cuisinier", undercover: "Serveur" },
  { civil: "Coiffeur", undercover: "Esthéticienne" },
  { civil: "Mécanicien", undercover: "Électricien" },
  { civil: "Vétérinaire", undercover: "Fermier" },
  { civil: "Journaliste", undercover: "Écrivain" },
  { civil: "Pilote", undercover: "Steward" },
  { civil: "Chirurgien", undercover: "Dentiste" },
  { civil: "Comptable", undercover: "Banquier" },
  { civil: "Notaire", undercover: "Huissier" },
  { civil: "Plombier", undercover: "Menuisier" },
  { civil: "Peintre", undercover: "Sculpteur" },
  { civil: "Photographe", undercover: "Vidéaste" },
  { civil: "Musicien", undercover: "Compositeur" },
  { civil: "Traducteur", undercover: "Interprète" },
  { civil: "Jardinier", undercover: "Paysagiste" },
  { civil: "Astronaute", undercover: "Cosmonaute" },
  { civil: "Marin", undercover: "Capitaine" },
  { civil: "Soldat", undercover: "Général" },
  { civil: "Espion", undercover: "Détective" },
  { civil: "Voleur", undercover: "Cambrioleur" },
  { civil: "Magicien", undercover: "Illusionniste" },
  { civil: "Clown", undercover: "Acrobate" },
  { civil: "Couturier", undercover: "Tailleur" },
  { civil: "Bijoutier", undercover: "Horloger" },
  { civil: "Libraire", undercover: "Éditeur" },
  { civil: "Guide", undercover: "Touriste" },
  { civil: "Agriculteur", undercover: "Éleveur" },
  { civil: "Basket", undercover: "Volley" },
  { civil: "Tennis", undercover: "Badminton" },
  { civil: "Natation", undercover: "Plongée" },
  { civil: "Boxe", undercover: "Judo" },
  { civil: "Escalade", undercover: "Randonnée" },
  { civil: "Golf", undercover: "Bowling" },
  { civil: "Cyclisme", undercover: "Triathlon" },
  { civil: "Handball", undercover: "Water-polo" },
  { civil: "Athlétisme", undercover: "Décathlon" },
  { civil: "Gymnastique", undercover: "Patinage" },
  { civil: "Karaté", undercover: "Taekwondo" },
  { civil: "Équitation", undercover: "Polo" },
  { civil: "Voile", undercover: "Aviron" },
  { civil: "Surf", undercover: "Bodyboard" },
  { civil: "Escrime", undercover: "Tir à l'arc" },
  { civil: "Pétanque", undercover: "Billard" },
  { civil: "Curling", undercover: "Hockey" },
  { civil: "Rafting", undercover: "Kayak" },
  { civil: "Parachutisme", undercover: "Parapente" },
  { civil: "Alpinisme", undercover: "Spéléologie" },
  { civil: "Table", undercover: "Chaise" },
  { civil: "Canapé", undercover: "Fauteuil" },
  { civil: "Lit", undercover: "Matelas" },
  { civil: "Armoire", undercover: "Commode" },
  { civil: "Tapis", undercover: "Rideau" },
  { civil: "Étagère", undercover: "Bibliothèque" },
  { civil: "Horloge", undercover: "Réveil" },
  { civil: "Aspirateur", undercover: "Balai" },
  { civil: "Machine à laver", undercover: "Sèche-linge" },
  { civil: "Four", undercover: "Micro-ondes" },
  { civil: "Grille-pain", undercover: "Bouilloire" },
  { civil: "Robinet", undercover: "Douche" },
  { civil: "Baignoire", undercover: "Lavabo" },
  { civil: "Coussin", undercover: "Oreiller" },
  { civil: "Couette", undercover: "Drap" },
  { civil: "Vase", undercover: "Cadre" },
  { civil: "Serrure", undercover: "Clé" },
  { civil: "Interrupteur", undercover: "Prise" },
  { civil: "Poubelle", undercover: "Recyclage" },
  { civil: "Éponge", undercover: "Chiffon" },
  { civil: "Chemise", undercover: "T-shirt" },
  { civil: "Pantalon", undercover: "Jean" },
  { civil: "Jupe", undercover: "Robe" },
  { civil: "Manteau", undercover: "Veste" },
  { civil: "Pull", undercover: "Gilet" },
  { civil: "Chaussure", undercover: "Botte" },
  { civil: "Ceinture", undercover: "Bretelle" },
  { civil: "Lunettes", undercover: "Lentilles" },
  { civil: "Bague", undercover: "Bracelet" },
  { civil: "Collier", undercover: "Boucle d'oreille" },
  { civil: "Sac à main", undercover: "Portefeuille" },
  { civil: "Parfum", undercover: "Déodorant" },
  { civil: "Maillot de bain", undercover: "Combinaison" },
  { civil: "Costume", undercover: "Smoking" },
  { civil: "Sandale", undercover: "Tong" },
  { civil: "Pain", undercover: "Baguette" },
  { civil: "Beurre", undercover: "Margarine" },
  { civil: "Lait", undercover: "Crème" },
  { civil: "Œuf", undercover: "Omelette" },
  { civil: "Riz", undercover: "Pâtes" },
  { civil: "Soupe", undercover: "Bouillon" },
  { civil: "Steak", undercover: "Côtelette" },
  { civil: "Poisson", undercover: "Fruits de mer" },
  { civil: "Salade", undercover: "Crudités" },
  { civil: "Gâteau", undercover: "Tarte" },
  { civil: "Glace", undercover: "Sorbet" },
  { civil: "Biscuit", undercover: "Gâteau sec" },
  { civil: "Jus", undercover: "Soda" },
  { civil: "Champagne", undercover: "Cidre" },
  { civil: "Whisky", undercover: "Rhum" },
  { civil: "Cocktail", undercover: "Mocktail" },
  { civil: "Épice", undercover: "Herbe aromatique" },
  { civil: "Moutarde", undercover: "Ketchup" },
  { civil: "Mayonnaise", undercover: "Vinaigrette" },
  { civil: "Nouilles", undercover: "Ramen" },
  { civil: "Sushi", undercover: "Sashimi" },
  { civil: "Curry", undercover: "Couscous" },
  { civil: "Raclette", undercover: "Fondue" },
  { civil: "Croissant", undercover: "Pain au chocolat" },
  { civil: "Macaron", undercover: "Éclair" },
  { civil: "Popcorn", undercover: "Chips" },
  { civil: "Barbecue", undercover: "Grill" },
  { civil: "École", undercover: "Université" },
  { civil: "Mairie", undercover: "Préfecture" },
  { civil: "Banque", undercover: "Poste" },
  { civil: "Supermarché", undercover: "Marché" },
  { civil: "Restaurant", undercover: "Bistrot" },
  { civil: "Hôtel", undercover: "Auberge" },
  { civil: "Usine", undercover: "Entrepôt" },
  { civil: "Ferme", undercover: "Ranch" },
  { civil: "Prison", undercover: "Commissariat" },
  { civil: "Stade", undercover: "Gymnase" },
  { civil: "Parc", undercover: "Square" },
  { civil: "Montagne", undercover: "Colline" },
  { civil: "Volcan", undercover: "Grotte" },
  { civil: "Île", undercover: "Continent" },
  { civil: "Vallée", undercover: "Plaine" },
  { civil: "Village", undercover: "Ville" },
  { civil: "Quartier", undercover: "Rue" },
  { civil: "Pont", undercover: "Tunnel" },
  { civil: "Phare", undercover: "Port" },
  { civil: "Usine", undercover: "Chantier" },
  { civil: "Caserne", undercover: "Camp militaire" },
  { civil: "Temple", undercover: "Mosquée" },
  { civil: "Synagogue", undercover: "Monastère" },
  { civil: "Palais", undercover: "Manoir" },
  { civil: "Tablette", undercover: "Liseuse" },
  { civil: "Casque", undercover: "Écouteurs" },
  { civil: "Imprimante", undercover: "Scanner" },
  { civil: "Appareil photo", undercover: "Caméra" },
  { civil: "Télévision", undercover: "Vidéoprojecteur" },
  { civil: "Batterie", undercover: "Chargeur" },
  { civil: "Drone", undercover: "Robot" },
  { civil: "Console", undercover: "Manette" },
  { civil: "Enceinte", undercover: "Micro" },
  { civil: "Réfrigérateur", undercover: "Congélateur" },
  { civil: "Ventilateur", undercover: "Climatiseur" },
  { civil: "Radiateur", undercover: "Cheminée" },
  { civil: "Boussole", undercover: "GPS" },
  { civil: "Jumelles", undercover: "Télescope" },
  { civil: "Calculatrice", undercover: "Ordinateur" },
  { civil: "Carte bancaire", undercover: "Espèces" },
  { civil: "Passeport", undercover: "Carte d'identité" },
  { civil: "Billet", undercover: "Ticket" },
  { civil: "Valise", undercover: "Sac de voyage" },
  { civil: "Tente", undercover: "Caravane" },
  { civil: "Arc-en-ciel", undercover: "Éclair" },
  { civil: "Nuage", undercover: "Brouillard" },
  { civil: "Vent", undercover: "Tornade" },
  { civil: "Séisme", undercover: "Tsunami" },
  { civil: "Cascade", undercover: "Geyser" },
  { civil: "Désert", undercover: "Oasis" },
  { civil: "Glacier", undercover: "Iceberg" },
  { civil: "Récif", undercover: "Corail" },
  { civil: "Marée", undercover: "Vague" },
  { civil: "Feu de forêt", undercover: "Éruption" },
  { civil: "Rosée", undercover: "Givre" },
  { civil: "Éclipse", undercover: "Aurore boréale" },
  { civil: "Comète", undercover: "Météorite" },
  { civil: "Galaxie", undercover: "Univers" },
  { civil: "Séisme", undercover: "Avalanche" },
  { civil: "Amour", undercover: "Amitié" },
  { civil: "Peur", undercover: "Angoisse" },
  { civil: "Joie", undercover: "Bonheur" },
  { civil: "Tristesse", undercover: "Nostalgie" },
  { civil: "Colère", undercover: "Rage" },
  { civil: "Jalousie", undercover: "Envie" },
  { civil: "Courage", undercover: "Bravoure" },
  { civil: "Honte", undercover: "Culpabilité" },
  { civil: "Fierté", undercover: "Confiance" },
  { civil: "Espoir", undercover: "Optimisme" },
  { civil: "Solitude", undercover: "Isolement" },
  { civil: "Curiosité", undercover: "Étonnement" },
  { civil: "Liberté", undercover: "Indépendance" },
  { civil: "Justice", undercover: "Équité" },
  { civil: "Vérité", undercover: "Mensonge" },
  { civil: "Rêve", undercover: "Cauchemar" },
  { civil: "Souvenir", undercover: "Oubli" },
  { civil: "Silence", undercover: "Bruit" },
  { civil: "Noël", undercover: "Pâques" },
  { civil: "Halloween", undercover: "Carnaval" },
  { civil: "Nouvel An", undercover: "Fête nationale" },
  { civil: "Baptême", undercover: "Communion" },
  { civil: "Enterrement", undercover: "Funérailles" },
  { civil: "Concert", undercover: "Festival" },
  { civil: "Exposition", undercover: "Salon" },
  { civil: "Conférence", undercover: "Séminaire" },
  { civil: "Compétition", undercover: "Tournoi" },
  { civil: "Déménagement", undercover: "Rénovation" },
  { civil: "Vacances", undercover: "Week-end" },
  { civil: "Réunion", undercover: "Rendez-vous" },
  { civil: "Batterie", undercover: "Percussion" },
  { civil: "Trompette", undercover: "Saxophone" },
  { civil: "Flûte", undercover: "Clarinette" },
  { civil: "Harpe", undercover: "Accordéon" },
  { civil: "Tambour", undercover: "Xylophone" },
  { civil: "Opéra", undercover: "Comédie musicale" },
  { civil: "Rap", undercover: "Rock" },
  { civil: "Jazz", undercover: "Blues" },
  { civil: "Classique", undercover: "Électro" },
  { civil: "Voiture", undercover: "Camionnette" },
  { civil: "Tracteur", undercover: "Bulldozer" },
  { civil: "Fusée", undercover: "Navette spatiale" },
  { civil: "Traîneau", undercover: "Luge" },
  { civil: "Char", undercover: "Tank" },
  { civil: "Ambulance", undercover: "Camion de pompiers" },
  { civil: "Taxi", undercover: "VTC" },
  { civil: "Téléphérique", undercover: "Funiculaire" },
  { civil: "Voiturette de golf", undercover: "Kart" },
  { civil: "Roller", undercover: "Patin à glace" },
  { civil: "Planche à voile", undercover: "Kitesurf" },
  { civil: "Cœur", undercover: "Poumon" },
  { civil: "Cerveau", undercover: "Colonne vertébrale" },
  { civil: "Muscle", undercover: "Os" },
  { civil: "Dent", undercover: "Gencive" },
  { civil: "Cheveu", undercover: "Ongle" },
  { civil: "Fièvre", undercover: "Rhume" },
  { civil: "Vaccin", undercover: "Médicament" },
  { civil: "Plâtre", undercover: "Pansement" },
  { civil: "Lunettes de soleil", undercover: "Casque de vélo" },
  { civil: "Béquille", undercover: "Fauteuil roulant" },
  { civil: "Seringue", undercover: "Thermomètre" },
  { civil: "Cahier", undercover: "Carnet" },
  { civil: "Stylo", undercover: "Crayon" },
  { civil: "Gomme", undercover: "Taille-crayon" },
  { civil: "Tableau", undercover: "Craie" },
  { civil: "Cartable", undercover: "Trousse" },
  { civil: "Examen", undercover: "Devoir" },
  { civil: "Récréation", undercover: "Cantine" },
  { civil: "Diplôme", undercover: "Certificat" },
  { civil: "Bibliothèque", undercover: "Salle de classe" },
  { civil: "Robot", undercover: "Extraterrestre" },
  { civil: "Vampire", undercover: "Zombie" },
  { civil: "Fantôme", undercover: "Squelette" },
  { civil: "Dragon", undercover: "Dinosaure" },
  { civil: "Pirate", undercover: "Corsaire" },
  { civil: "Chevalier", undercover: "Gladiateur" },
  { civil: "Superhéros", undercover: "Vilain" },
  { civil: "Ange", undercover: "Démon" },
  { civil: "Licorne", undercover: "Pégase" },
  { civil: "Sirène", undercover: "Triton" },
  { civil: "Géant", undercover: "Nain" },
  { civil: "Sorcier", undercover: "Alchimiste" },
  { civil: "Momie", undercover: "Pharaon" },
  { civil: "Loup-garou", undercover: "Sorcière" },
  { civil: "Elfe", undercover: "Gobelin" },
  { civil: "Jeu vidéo", undercover: "Jeu de société" },
  { civil: "Puzzle", undercover: "Mots croisés" },
  { civil: "Échecs", undercover: "Dames" },
  { civil: "Cartes à jouer", undercover: "Dominos" },
  { civil: "Loto", undercover: "Bingo" },
  { civil: "Casino", undercover: "Machine à sous" },
  { civil: "Fête foraine", undercover: "Manège" },
  { civil: "Montagnes russes", undercover: "Grande roue" },
  { civil: "Feu d'artifice", undercover: "Pétard" },
  { civil: "Poupée", undercover: "Peluche" },
  { civil: "Toboggan", undercover: "Balançoire" },
  { civil: "Cerf-volant", undercover: "Frisbee" },
  { civil: "Origami", undercover: "Sculpture sur bois" },
  { civil: "Poterie", undercover: "Céramique" },
  { civil: "Broderie", undercover: "Tricot" },
  { civil: "Photographie", undercover: "Peinture" },
  { civil: "Cinéma", undercover: "Streaming" },
  { civil: "Podcast", undercover: "Émission de radio" },
  { civil: "Roman", undercover: "Bande dessinée" },
  { civil: "Poème", undercover: "Chanson" },
  { civil: "Blague", undercover: "Devinette" },
  { civil: "Proverbe", undercover: "Citation" },
  { civil: "Légende", undercover: "Mythe" },
  { civil: "Conte", undercover: "Fable" },
  { civil: "Abricot", undercover: "Pêche" },
  { civil: "Datte", undercover: "Figue" },
  { civil: "Grenade", undercover: "Litchi" },
  { civil: "Coriandre", undercover: "Persil" },
  { civil: "Basilic", undercover: "Menthe" },
  { civil: "Cannelle", undercover: "Vanille" },
  { civil: "Gingembre", undercover: "Curcuma" },
  { civil: "Safran", undercover: "Paprika" },
  { civil: "Sauge", undercover: "Thym" },
  { civil: "Lynx", undercover: "Puma" },
  { civil: "Guépard", undercover: "Léopard" },
  { civil: "Hyène", undercover: "Chacal" },
  { civil: "Antilope", undercover: "Gazelle" },
  { civil: "Bison", undercover: "Yack" },
  { civil: "Élan", undercover: "Cerf" },
  { civil: "Sanglier", undercover: "Marcassin" },
  { civil: "Furet", undercover: "Belette" },
  { civil: "Vison", undercover: "Hermine" },
  { civil: "Corbeau", undercover: "Pie" },
  { civil: "Moineau", undercover: "Rossignol" },
  { civil: "Pélican", undercover: "Cormoran" },
  { civil: "Ibis", undercover: "Héron" },
  { civil: "Vautour", undercover: "Buse" },
  { civil: "Colibri", undercover: "Toucan" },
  { civil: "Iguane", undercover: "Caméléon" },
  { civil: "Salamandre", undercover: "Triton" },
  { civil: "Gecko", undercover: "Varan" },
  { civil: "Piranha", undercover: "Barracuda" },
  { civil: "Anguille", undercover: "Murène" },
  { civil: "Hippocampe", undercover: "Poisson-clown" },
  { civil: "Étoile de mer", undercover: "Oursin" },
  { civil: "Homard", undercover: "Écrevisse" },
  { civil: "Huître", undercover: "Moule" },
  { civil: "Termite", undercover: "Cafard" },
  { civil: "Sauterelle", undercover: "Criquet" },
  { civil: "Libellule", undercover: "Demoiselle" },
  { civil: "Frelon", undercover: "Guêpe" },
  { civil: "Puce", undercover: "Tique" },
  { civil: "Ver luisant", undercover: "Luciole" },
  { civil: "Boucher", undercover: "Charcutier" },
  { civil: "Fleuriste", undercover: "Pépiniériste" },
  { civil: "Chauffeur", undercover: "Livreur" },
  { civil: "Douanier", undercover: "Agent de sécurité" },
  { civil: "Serrurier", undercover: "Vitrier" },
  { civil: "Tapissier", undercover: "Décorateur" },
  { civil: "Chercheur", undercover: "Scientifique" },
  { civil: "Psychologue", undercover: "Psychiatre" },
  { civil: "Kinésithérapeute", undercover: "Ostéopathe" },
  { civil: "Sage-femme", undercover: "Pédiatre" },
  { civil: "Ambulancier", undercover: "Secouriste" },
  { civil: "Douanier", undercover: "Gendarme" },
  { civil: "Maçon", undercover: "Charpentier" },
  { civil: "Peintre en bâtiment", undercover: "Carreleur" },
  { civil: "Chauffagiste", undercover: "Couvreur" },
  { civil: "Vendeur", undercover: "Caissier" },
  { civil: "Réceptionniste", undercover: "Concierge" },
  { civil: "Barman", undercover: "Sommelier" },
  { civil: "Pâtissier", undercover: "Chocolatier" },
  { civil: "Traiteur", undercover: "Restaurateur" },
  { civil: "Éleveur", undercover: "Dresseur" },
  { civil: "Apiculteur", undercover: "Viticulteur" },
  { civil: "Bûcheron", undercover: "Forestier" },
  { civil: "Mineur", undercover: "Carrier" },
  { civil: "Squash", undercover: "Ping-pong" },
  { civil: "Fléchettes", undercover: "Billard" },
  { civil: "Aïkido", undercover: "Kung-fu" },
  { civil: "Sumo", undercover: "Lutte" },
  { civil: "Haltérophilie", undercover: "Musculation" },
  { civil: "Fitness", undercover: "Yoga" },
  { civil: "Pilates", undercover: "Stretching" },
  { civil: "Trail", undercover: "Cross-country" },
  { civil: "Biathlon", undercover: "Ski de fond" },
  { civil: "Bobsleigh", undercover: "Luge" },
  { civil: "Rodéo", undercover: "Tauromachie" },
  { civil: "Chasse", undercover: "Pêche" },
  { civil: "Canoë", undercover: "Pirogue" },
  { civil: "Stand up paddle", undercover: "Planche à voile" },
  { civil: "Plongeon", undercover: "Water-polo" },
  { civil: "Torchon", undercover: "Serviette" },
  { civil: "Panier", undercover: "Corbeille" },
  { civil: "Cintre", undercover: "Portant" },
  { civil: "Étendoir", undercover: "Fer à repasser" },
  { civil: "Balai", undercover: "Serpillière" },
  { civil: "Seau", undercover: "Bassine" },
];

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = a[i] as T;
    a[i] = a[j] as T;
    a[j] = tmp;
  }
  return a;
}

export function maxUndercover(players: number) {
  return Math.min(3, Math.max(1, players - 1));
}

export function maxMrWhite(players: number, undercover: number) {
  // civils must be strictly more than half of the players
  const minCivils = Math.floor(players / 2) + 1;
  return Math.max(0, Math.min(2, players - minCivils - undercover));
}

export function isValidSetup(players: number, undercover: number, mrWhite: number) {
  const civils = players - undercover - mrWhite;
  return players >= 3 && players <= 10 && undercover >= 1 && mrWhite >= 0 && civils > players / 2;
}

export type Game = {
  pair: WordPair;
  players: Player[];
  roundStarterOrder: number; // order index of the first speaker
};

export function createGame(playerCount: number, undercover: number, mrWhite: number): Game {
  const pair = WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)] as WordPair;
  const roles: Role[] = [
    ...Array.from({ length: undercover }, () => "undercover" as Role),
    ...Array.from({ length: mrWhite }, () => "mrwhite" as Role),
    ...Array.from({ length: playerCount - undercover - mrWhite }, () => "civil" as Role),
  ];
  const shuffled = shuffle(roles);
  const players: Player[] = shuffled.map((role, i) => ({
    id: i,
    cardIndex: i,
    order: -1,
    name: "",
    role,
    word: role === "civil" ? pair.civil : role === "undercover" ? pair.undercover : null,
    eliminated: false,
  }));
  return { pair, players, roundStarterOrder: 0 };
}

export function pickStarter(players: Player[]): number {
  const ordered = players.filter((p) => !p.eliminated).sort((a, b) => a.order - b.order);
  const eligible = ordered.filter((p) => p.role !== "mrwhite");
  const chosen =
    eligible.length > 0 ? eligible[Math.floor(Math.random() * eligible.length)] : ordered[0];
  return chosen ? chosen.order : 0;
}

export function speakingOrder(players: Player[], starterOrder: number): Player[] {
  const alive = players.filter((p) => !p.eliminated).sort((a, b) => a.order - b.order);
  const start = alive.findIndex((p) => p.order === starterOrder);
  if (start <= 0) return alive;
  return [...alive.slice(start), ...alive.slice(0, start)];
}

export type Outcome = "civils" | "impostors" | null;

export function checkOutcome(players: Player[]): Outcome {
  const alive = players.filter((p) => !p.eliminated);
  const impostors = alive.filter((p) => p.role !== "civil").length;
  const civils = alive.filter((p) => p.role === "civil").length;
  if (impostors === 0) return "civils";
  if (civils <= 1) return "impostors";
  return null;
}

export function normalizeWord(w: string) {
  return w
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
}

export const ROLE_LABEL: Record<Role, string> = {
  civil: "Civil",
  undercover: "Undercover",
  mrwhite: "Mr White",
};
